# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'

trigger:
- master

steps:
- task: CocoaPods@0
  displayName: 'pod install using the CocoaPods task with defaults'
  inputs:
    forceRepoUpdate: true
    workingDirectory: 'AzureTest'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'AzureTest'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'AzureTest.xcworkspace'
    packageApp: true
    archivePath: output/$(SDK)/$(Configuration)
    exportPath: 'output/$(SDK)/$(Configuration)' # Optional

